name: flutter_cmoon_icons
description: Flutter Icons package Insipred by Font Awesome package, his package contains more than 2000 icons
version: 0.0.2+1
homepage: https://github.com/Rexfordasamoah51/flutter_cMoon_icons.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  
  
   fonts:
    - family: icomoon
      fonts:
        - asset: lib/fonts/icomoon.ttf
 
 